### ISSUE TITLE
Conflict with Natural Language Dates Plugin

### ISSUE THREAD

**Issue by JensDienst** [saibotsivad/obsidian-at-people#2]
Hi, 

if the Natural Language Dates plugin is installed and left in its Default Configuration the @ Mentions are conflicting. 

Greetings
Jens

**Comment by saibotsivad** [comment]
I'm exploring this problem as well, because I find the `EditorSuggest` doesn't work well together with the Tasks plugin. As far as I can tell so far, there's no way to merge multiple `EditorSuggest` suggestions, and no way to specify precedence, which is frustrating.

However, tor the NLD plugin specifically, you can [change the trigger phrase](https://github.com/argenos/nldates-obsidian#configuration), so that's one option.

**Comment by beingskyler** [comment]
@saibotsivad - Just to be clear, you closed this because changing the trigger phrase for the NLD plugin is an option? As opposed to what the [@ Symbol Linking plugin](https://github.com/Ebonsignori/obsidian-at-symbol-linking) did by adding a compatibility mode so users can continue using the `@` trigger for both references people (or anything for that matter) and the NLD plugin?

**Comment by saibotsivad** [comment]
I closed it because, when it was opened **9 months ago**, I had not found an Obsidian-native way to handle multiple `EditorSuggest` instances.

As far as I can tell from the Obsidian docs this is still not possible to do natively. (If you have links to Obsidian docs that suggest otherwise I would genuinely love it, this is a real annoyance to me.)

Looking at the trouble the Symbol Linking plugin has to go through to implement a custom suggestion box ([see source](https://github.com/Ebonsignori/obsidian-at-symbol-linking/tree/c1f854b7ea5bef5ac919c5b4ca6e9d7514205fae/src/compatibility-mode-extension)) makes me uncomfortable adding that to this plugin, so I'll leave this closed still.

Hopefully Obsidian implements a better `EditorSuggest` management cycle.
